theme: jekyll-theme-midnight
title: Welcome to Tito's Totally Adequete RISC-V Repo & Kind of, Sort of - Homepage
description: This is a working project learning RISC-V open source learning chipset via XV6 - following MITs Introduction to Operating Systems from Fall 2020. Feel free to DM me with suggestions or ideas to work together in the future. 
